package config

import "time"

// LoadBalancingPolicy identifies an endpoint-selection policy for an upstream.
type LoadBalancingPolicy string

// LoadBalancingPolicyRoundRobin selects endpoints in cyclic order.
const LoadBalancingPolicyRoundRobin LoadBalancingPolicy = "round_robin"

// RouteConfig describes one gateway route loaded from the configuration file.
type RouteConfig struct {
	Name                string                      `yaml:"name"`
	Protocol            string                      `yaml:"protocol"`
	PathPrefix          string                      `yaml:"path_prefix"`
	PathExact           string                      `yaml:"path_exact"`
	HeaderMatches       []HeaderMatchConfig         `yaml:"header_matches"`
	Methods             []string                    `yaml:"methods"`
	Hosts               []string                    `yaml:"hosts"`
	Priority            int                         `yaml:"priority"`
	UpstreamURL         string                      `yaml:"upstream_url"`
	Upstream            *UpstreamConfig             `yaml:"upstream"`
	DirectResponse      *DirectResponseConfig       `yaml:"direct_response"`
	Redirect            *RedirectConfig             `yaml:"redirect"`
	ErrorResponses      map[int]ErrorResponseConfig `yaml:"error_responses"`
	RateLimit           *RateLimitConfig            `yaml:"rate_limit"`
	StripPathPrefix     bool                        `yaml:"strip_path_prefix"`
	RequestTimeout      time.Duration               `yaml:"request_timeout"`
	MaxRequestBodyBytes int64                       `yaml:"max_request_body_bytes"`
	RequestHeaders      *HeaderTransformConfig      `yaml:"request_headers"`
	ResponseHeaders     *HeaderTransformConfig      `yaml:"response_headers"`
}

// HeaderTransformConfig describes static header values to set and header names
// to remove when applying a route's header policy.
type HeaderTransformConfig struct {
	Set    map[string]string `yaml:"set"`
	Remove []string          `yaml:"remove"`
}

// RateLimitConfig configures a local token-bucket rate limiter for a route.
type RateLimitConfig struct {
	RequestsPerSecond float64 `yaml:"requests_per_second"`
	Burst             int     `yaml:"burst"`
}

// DirectResponseConfig configures a static HTTP response returned without
// forwarding the request to an upstream.
type DirectResponseConfig struct {
	StatusCode int    `yaml:"status"`
	Body       string `yaml:"body"`
}

// RedirectConfig configures an HTTP redirect returned without forwarding the
// request to an upstream.
type RedirectConfig struct {
	StatusCode int    `yaml:"status"`
	Location   string `yaml:"location"`
}

// ErrorResponseConfig configures the body and headers of an error response
// generated by DevGate.
type ErrorResponseConfig struct {
	Body    string            `yaml:"body"`
	Headers map[string]string `yaml:"headers"`
}

// HeaderMatchConfig describes an exact request header condition for a route.
type HeaderMatchConfig struct {
	Name  string `yaml:"name"`
	Exact string `yaml:"exact"`
}

// UpstreamConfig configures endpoint discovery and load balancing for an
// upstream route.
type UpstreamConfig struct {
	LoadBalancing LoadBalancingPolicy      `yaml:"load_balancing"`
	Discovery     *UpstreamDiscoveryConfig `yaml:"discovery"`
}

// UpstreamDiscoveryConfig selects one source of upstream endpoints.
type UpstreamDiscoveryConfig struct {
	Static *StaticUpstreamDiscoveryConfig `yaml:"static"`
}

// StaticUpstreamDiscoveryConfig defines endpoints supplied directly in the
// configuration file.
type StaticUpstreamDiscoveryConfig struct {
	Endpoints []UpstreamEndpointConfig `yaml:"endpoints"`
}

// UpstreamEndpointConfig identifies one statically configured upstream
// endpoint.
type UpstreamEndpointConfig struct {
	URL string `yaml:"url"`
}

type fileConfig struct {
	Routes         []RouteConfig               `yaml:"routes"`
	ErrorResponses map[int]ErrorResponseConfig `yaml:"error_responses"`
}
